import { copyFile, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const APP = path.resolve(import.meta.dirname, '..');
const DIST = path.resolve(APP, '../../content/dist');

const manifest = JSON.parse(await readFile(path.join(DIST, 'manifest.json'), 'utf8')) as {
  version: number;
  bundlePath: string;
  imagesPath: string;
};

const assetsDir = path.join(APP, 'assets', 'content');
const contentDir = path.join(APP, 'src', 'content');
await rm(assetsDir, { recursive: true, force: true });
await mkdir(assetsDir, { recursive: true });
await mkdir(contentDir, { recursive: true });

await copyFile(path.join(DIST, manifest.bundlePath), path.join(contentDir, 'bundle.json'));

const images = (await readdir(path.join(DIST, manifest.imagesPath))).filter((file) => file.endsWith('.webp')).sort();
for (const file of images) await copyFile(path.join(DIST, manifest.imagesPath, file), path.join(assetsDir, file));

const entries = images.map((file) => `  '${file.slice(0, -'.webp'.length)}': require('../../assets/content/${file}'),`);
await writeFile(
  path.join(contentDir, 'images.ts'),
  `// Generated by scripts/sync-content.mts from content v${manifest.version}. Do not edit.\n\nexport const IMAGES: Record<string, number> = {\n${entries.join('\n')}\n};\n`,
);

console.log(`Synced content v${manifest.version}: ${images.length} images`);
