// Generated by scripts/sync-content.mts from content v1. Do not edit.

export const IMAGES: Record<string, number> = {
  'body-front': require('../../assets/content/body-front.webp'),
  'cat-shoulder': require('../../assets/content/cat-shoulder.webp'),
  'hand-dorsal': require('../../assets/content/hand-dorsal.webp'),
};
